version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: rcps-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rcps
      POSTGRES_PASSWORD: rcps
      POSTGRES_DB: rcps
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
